apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ggzd
  name: ggzd
spec:
  finalizers:
  - kubernetes

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ggzd
#  namespace: argocd
spec:
  destination:
    namespace: ggzd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ggzd
    repoURL: https://github.com/boudewijnatpink/apps.git
    targetRevision: main
  syncPolicy: {}
