apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ggzb26
  name: ggzb26
spec:
  finalizers:
  - kubernetes

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ggzb26
#  namespace: argocd
spec:
  destination:
    namespace: ggzb26
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ggzb26
    repoURL: https://github.com/boudewijnatpink/apps.git
    targetRevision: main
  syncPolicy: {}
