apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ggzc
  name: ggzc
spec:
  finalizers:
  - kubernetes

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ggzc
#  namespace: argocd
spec:
  destination:
    namespace: ggzc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ggzc
    repoURL: https://github.com/boudewijnatpink/apps.git
    targetRevision: main
  syncPolicy: {}
