apiVersion: apps/v1
kind: Deployment
metadata: {name: api--dmz}
spec:
  replicas: 1
  selector:
    matchLabels: {app: api--dmz}
  template:
    metadata:
      labels: {app: api--dmz}
    spec:
      containers:
      - envFrom:
        - configMapRef: 
            name: api--dmz--api
        - configMapRef: 
            name: dbconfigmap
        image: nexus-docker-releases.hchosting.nl/api:1.3.39.0
        name: api--dmz--api
      - envFrom:
        - configMapRef: {name: api--dmz--http2https}
        image: nexus-docker-releases.hchosting.nl/http2https:1.4.0
        name: api--dmz--http2https
      - name: ubuntu
        image: ubuntu
        args: [/bin/sh, -c,'i=0; while true; do echo "Hello World nr: $i"; i=$((i+1)); sleep 1; done'] 
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: dbconfigmap 
#  behavior: create
data:
  qwport: "3306"
  qwhost: remotehost
  qwalt: yaremotehost

