apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ggzb21
  name: ggzb21
spec:
  finalizers:
  - kubernetes

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ggzb21
#  namespace: argocd
spec:
  destination:
    namespace: ggzb21
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/ggzb21
    repoURL: https://github.com/boudewijnatpink/apps.git
    targetRevision: main
  syncPolicy: {}
